export enum DmaSkuProjectEnum {
  PRODUCT_OF_THE_DAY = 0,
  ADDITIONAL_LAYOUT = 1,
  VOLUME_PRICE_REDUCTION = 2,
  TEMPORARY_PRICE_REDUCTION = 3,
  ADDITIONAL_INVENTORY = 4,
  BEST_PRICE = 5,
  PRODUCT_INFORMATION = 6,
  POSM = 7
}
