export class BasicMarketingTest {
    static withOutSku: any = {
        'dataFrom': 0,
        'basicMarketingActivityType': 0,
        'hasVat': false,
        'organicGrowth': 0,
        'investmentPercentage': 0,
        'estimatedInvestmentsForPeriodPrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'oneSkuReportPricePrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'actualReportingPeriodFrom': '2020-03-01T00:00:00',
        'actualReportingPeriodTo': '2020-03-01T00:00:00',
        'ntzAmountPrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'calculationAmountPrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'reportsAmountPrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'totalFactOldPrice': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'totalPlanNow': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'matrixInvestmentsYear': {'pricesDDP': 1, 'pricesDDPContract': 1, 'pricesNet': 1},
        'matrixInvestmentsMonth': {'pricesDDP': 1, 'pricesDDPContract': 1, 'pricesNet': 1},
        'investmentsFact': {'pricesDDP': 1, 'pricesDDPContract': 1, 'pricesNet': 1},
        'directPosting': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'reverse': {'pricesDDP': -1, 'pricesDDPContract': -1, 'pricesNet': -1},
        'originalAmount': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'currentAmount': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'delta': {'pricesDDP': 0, 'pricesDDPContract': 0, 'pricesNet': 0},
        'basicMarketingSkus': [],
        'id': '732d38d8-0eca-4ae3-ac48-32e686b799df',
        'version': 2,
        'created': '2020-03-30T11:21:23.201438',
        'activityType': 1,
        'marketingPlanId': 53,
        'marketingPlan': {
            'periodFrom': '2020-03-01T00:00:00',
            'periodTo': '2020-03-01T00:00:00',
            'activityStatus': 0,
            'id': 53,
            'created': '2020-03-30T11:20:35.1461075',
            'modified': '2020-03-30T11:27:22.4942574',
            'pharmacyNetworkId': 68,
            'pharmacyNetwork': {
                'id': 68,
                'name': 'Меморандум',
                'legalEntityName': 'Меморандум',
                'legalForm': null,
                'category': 'ТОП',
                'segment': 'А1',
                'territory': null,
                'region': 'Москва',
                'kamId': 37,
                'kam': {
                    'id': 37,
                    'fullName': 'Kam Kam Kam',
                    'email': 'kam1@test.ru',
                    'position': 'KAM',
                    'roleId': 2,
                    'roleName': null,
                    'abbottID': 1234,
                    'prop511': 'abc4',
                    'status': 1
                },
                'akamId': 38,
                'akam': {
                    'id': 38,
                    'fullName': 'Akam Akam Akam',
                    'email': 'akam',
                    'position': 'akam@test.ru',
                    'roleId': 3,
                    'roleName': null,
                    'abbottID': 12345,
                    'prop511': 'abc5',
                    'status': 1
                },
                'totalOfPharmacies': 150,
                'networkType': 1,
                'procurementPlans': []
            },
            'baseScenarioSkus': [],
            'history': []
        },
        'activityStatus': 0,
        'addToJointAgreement': false,
        'comments': [],
        'periodFrom': '2020-03-01T00:00:00',
        'periodTo': '2020-03-01T00:00:00',
        'activityPeriodFrom': '2020-03-01T00:00:00',
        'activityPeriodTo': '2020-03-01T00:00:00',
        'activityDocument': {
            'id': 1452,
            'activityId': '732d38d8-0eca-4ae3-ac48-32e686b799df',
            'activityVersion': 2,
            'docNumber': '0',
            'docDateFrom': '2020-03-30T14:20:51',
            'additionalAgreementNumber': '',
            'applicationNumber': '',
            'iDworkflow': 0
        },
        'units': 0
    };
    static withSku: any = {
        "dataFrom": 0,
        "basicMarketingActivityType": 0,
        "hasVat": false,
        "organicGrowth": 20,
        "investmentPercentage": 15,
        "estimatedInvestmentsForPeriodPrice": {"pricesDDP": 500, "pricesDDPContract": 0, "pricesNet": 0},
        "oneSkuReportPricePrice": {"pricesDDP": 300, "pricesDDPContract": 0, "pricesNet": 0},
        "actualReportingPeriodFrom": "2020-04-01T00:00:00",
        "actualReportingPeriodTo": "2020-04-01T00:00:00",
        "ntzAmountPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "calculationAmountPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "reportsAmountPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "totalFactOldPrice": {"pricesDDP": 100, "pricesDDPContract": 0, "pricesNet": 0},
        "totalPlanNow": {"pricesDDP": 1000000, "pricesDDPContract": 0, "pricesNet": 0},
        "matrixInvestmentsYear": {"pricesDDP": 1, "pricesDDPContract": 1, "pricesNet": 1},
        "matrixInvestmentsMonth": {"pricesDDP": 1, "pricesDDPContract": 1, "pricesNet": 1},
        "investmentsFact": {"pricesDDP": 1, "pricesDDPContract": 1, "pricesNet": 1},
        "directPosting": {"pricesDDP": 500, "pricesDDPContract": 0, "pricesNet": 0},
        "reverse": {"pricesDDP": 499, "pricesDDPContract": -1, "pricesNet": -1},
        "originalAmount": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "currentAmount": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "delta": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
        "basicMarketingSkus": [{
            "id": 5125,
            "basicMarketingId": "a094c413-1c1a-4123-8301-2cc7c4d83f06",
            "basicMarketingVersion": 3,
            "skuId": 6,
            "sku": {
                "id": 6,
                "code": 0,
                "name": "Физиотенз 0,2 №28",
                "description": null,
                "rumdmName": null,
                "ta": null,
                "inactive": false,
                "axdx": null,
                "otc": false,
                "promoted": false,
                "safetyStockDays": 0,
                "marginality": 0,
                "priceDDP": 0,
                "priceDDPContract": 0,
                "priceNet": 0,
                "ddpPrices": [],
                "netPrices": [],
                "updateTime": null,
                "brand": {
                    "id": 1,
                    "code": 0,
                    "name": "Бетасерк",
                    "description": null,
                    "updateTime": null,
                    "businessUnit": null
                }
            },
            "ntzOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "ntzCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "reportsOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "reportsCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "ntzEqualsOne": 14,
            "ntzMoreOnePacks": 15,
            "ntzMoreOneDots": 16,
            "ntzMoreOneTotal": 17,
            "facetingNumber": 18,
            "calculationNumber": 19,
            "skuAmount": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationPlace": 0,
            "deviationFactFromPlanNTZ": 0.01,
            "deviationFactFromPlanCalculation": 0.01,
            "hasReports": false,
            "finesTotal": {"pricesDDP": 100, "pricesDDPContract": 100, "pricesNet": 100},
            "skuTotal": {"pricesDDP": 1000, "pricesDDPContract": 1000, "pricesNet": 1000}
        }, {
            "id": 5126,
            "basicMarketingId": "a094c413-1c1a-4123-8301-2cc7c4d83f06",
            "basicMarketingVersion": 3,
            "skuId": 8,
            "sku": {
                "id": 8,
                "code": 0,
                "name": "Физиотенз 0,4 №28",
                "description": null,
                "rumdmName": null,
                "ta": null,
                "inactive": false,
                "axdx": null,
                "otc": false,
                "promoted": false,
                "safetyStockDays": 0,
                "marginality": 0,
                "priceDDP": 0,
                "priceDDPContract": 0,
                "priceNet": 0,
                "ddpPrices": [],
                "netPrices": [],
                "updateTime": null,
                "brand": {
                    "id": 1,
                    "code": 0,
                    "name": "Бетасерк",
                    "description": null,
                    "updateTime": null,
                    "businessUnit": null
                }
            },
            "ntzOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "ntzCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "reportsOriginalPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "reportsCurrentPrice": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "ntzEqualsOne": 0,
            "ntzMoreOnePacks": 0,
            "ntzMoreOneDots": 0,
            "ntzMoreOneTotal": 0,
            "facetingNumber": 0,
            "calculationNumber": 0,
            "skuAmount": {"pricesDDP": 0, "pricesDDPContract": 0, "pricesNet": 0},
            "calculationPlace": 0,
            "deviationFactFromPlanNTZ": 0.01,
            "deviationFactFromPlanCalculation": 0.01,
            "hasReports": false,
            "finesTotal": {"pricesDDP": 100, "pricesDDPContract": 100, "pricesNet": 100},
            "skuTotal": {"pricesDDP": 1000, "pricesDDPContract": 1000, "pricesNet": 1000}
        }],
        "id": "a094c413-1c1a-4123-8301-2cc7c4d83f06",
        "version": 3,
        "code": 312,
        "created": "2020-04-02T08:55:20.4874528",
        "activityType": 1,
        "marketingPlanId": 6,
        "marketingPlan": {
            "periodFrom": "2020-03-01T00:00:00",
            "periodTo": "2020-03-01T00:00:00",
            "activityStatus": 0,
            "marketingPlanConditions": null,
            "id": 6,
            "created": "2020-03-15T13:23:22.1798829",
            "modified": "2020-04-02T15:06:12.3161798",
            "pharmacyNetworkId": 68,
            "pharmacyNetwork": {
                "id": 68,
                "name": "Меморандум",
                "legalEntityName": "Меморандум",
                "legalForm": null,
                "category": "ТОП",
                "segment": "А1",
                "territory": null,
                "region": "Москва",
                "kamId": 37,
                "kam": {
                    "id": 37,
                    "fullName": "Kam Kam Kam",
                    "email": "kam1@test.ru",
                    "position": "KAM",
                    "roleId": 2,
                    "roleName": null,
                    "abbottID": 1234,
                    "prop511": "abc4",
                    "status": 1
                },
                "akamId": 38,
                "akam": {
                    "id": 38,
                    "fullName": "Akam Akam Akam",
                    "email": "alexejtest20@gmail.com",
                    "position": "akam@test.ru",
                    "roleId": 3,
                    "roleName": null,
                    "abbottID": 12345,
                    "prop511": "abc5",
                    "status": 1
                },
                "totalOfPharmacies": 150,
                "networkType": 1,
                "procurementPlans": []
            },
            "baseScenarioSkus": [],
            "history": []
        },
        "activityStatus": 1,
        "addToJointAgreement": false,
        "comments": [{
            "id": 1744,
            "role": 2,
            "userId": 45,
            "user": {
                "id": 45,
                "fullName": "KAM KAM KAM",
                "email": "kam@test.ru",
                "position": "kam",
                "roleId": 2,
                "roleName": null,
                "abbottID": 139,
                "prop511": "125",
                "status": 1
            },
            "message": "666",
            "date": "2020-04-01T00:00:00",
            "activityId": "a094c413-1c1a-4123-8301-2cc7c4d83f06",
            "activityVersion": 3
        }],
        "periodFrom": "2020-04-01T00:00:00",
        "periodTo": "2020-04-01T00:00:00",
        "activityPeriodFrom": "2020-04-01T00:00:00",
        "activityPeriodTo": "2020-04-01T00:00:00",
        "activityDocument": {
            "id": 1839,
            "activityId": "a094c413-1c1a-4123-8301-2cc7c4d83f06",
            "activityVersion": 3,
            "docNumber": "5",
            "docDateFrom": "2020-04-05T00:00:00",
            "additionalAgreementNumber": "5",
            "applicationNumber": "5",
            "iDworkflow": 0
        },
        "units": 0
    };
}